# Numpy Practice 
#### First import numpy

In [2]:
import numpy as np

In [15]:
print(np)

<module 'numpy' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\numpy\\__init__.py'>


## Types of Matrix using numpy
1. Row matrix
2. Column matrix
3. Square matrix
4. Identity matrix
5. Zero matrix
6. Ones matrix
7. Random matrix
8. Diagonal matrix
9. Upper triangular matrix
10. Lower triangular  matrix
11. Symmetric matrix
12. Vander matrix
13. Hankel matrix


In [12]:
# row matrix

ro_matrix = np.array([[1,2,5,6]])
print(ro_matrix)

[[1 2 5 6]]


In [13]:
# column matrix

col_matrix = np.array([[9],[7],[6]])
print(col_matrix)

[[9]
 [7]
 [6]]


In [4]:
# simple 3*3 matrix or square matrix

matrix = np.array([[0,1,2],[3,4,5],[6,7,8]])
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [6]:
# identity matrix

i_matrix = np.eye(4)
print(i_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [16]:
# zero matrix

z_matrix = np.zeros((3,2))
print(z_matrix)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [11]:
# ones matrix

o_matrix = np.ones((2,4))
print(o_matrix)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [13]:
# random matrix

r_matrix = np.random.randint(0,15,(2,4))
print(r_matrix)

[[ 9  7  6 11]
 [ 1  0  9  2]]


In [16]:
# diagonal matrix

d_matrix = np.diag([4,7,9])
print(d_matrix)

[[4 0 0]
 [0 7 0]
 [0 0 9]]


In [17]:
# upper triangular matrix

up_matrix = np.triu([[22,12,11],[11,23,24],[44,56,88]])
print(up_matrix)

[[22 12 11]
 [ 0 23 24]
 [ 0  0 88]]


In [23]:
# lower triangular matrix

lw_matrix = np.tril([[14,16,18],[19,8,23],[9,7,3]])
print(lw_matrix)

[[14  0  0]
 [19  8  0]
 [ 9  7  3]]


In [24]:
# symmetric matrix

sy_matrix = np.array([[1, 2, 3], [2, 4, 5], [3, 5, 6]])
print(sy_matrix)

[[1 2 3]
 [2 4 5]
 [3 5 6]]


In [18]:
# symmetric matrix using random values

n = 4  # Size of the matrix
sym_matrix = np.random.randint(1,20,(n, n))
sym_matrix = (sym_matrix + sym_matrix.T) / 2 

print(sym_matrix)

[[13.   8.  14.5 14.5]
 [ 8.   7.   9.  12. ]
 [14.5  9.  15.  12. ]
 [14.5 12.  12.  18. ]]


In [25]:
# vander matrix: A matrix in which each column is a power of the vector input.

vander_matrix = np.vander([2, 3, 5,6])
print(vander_matrix)

[[  8   4   2   1]
 [ 27   9   3   1]
 [125  25   5   1]
 [216  36   6   1]]


In [29]:
# hankel matrix: A matrix in which each ascending diagonal from left to right is constant.

hankel_matrix = np.array([[1, 2, 3,6], [2, 3, 6,4], [3,6, 4, 5],[6,7,3,1]])
print(hankel_matrix)

[[1 2 3 6]
 [2 3 6 4]
 [3 6 4 5]
 [6 7 3 1]]


In [3]:
# hankel matrix: A matrix in which each ascending diagonal from left to right is constant.

hankel_matrix = np.array([[1, 2, 3,6], [2, 3, 6,4], [3,6, 4, 5],[6,7,3,1]])
print(hankel_matrix)

[[1 2 3 6]
 [2 3 6 4]
 [3 6 4 5]
 [6 7 3 1]]
